[package]
name = "devserver_lib"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"
keywords = ["web", "http"]

[lib]
name = "devserver_lib"

[dependencies]
native-tls = "0.2"
